# .github/workflows/e2e-smoke.yml
name: E2E • Smoke
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'e2e/**'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --frozen-lockfile
      - run: yarn build # 👉 ต้อง build ก่อน webServer

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run smoke tests
        run: yarn e2e:smoke # = playwright test --grep @smoke

      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
