# .github/workflows/e2e-smoke.yml
name: E2E - Smoke

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'e2e/**'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # .github/workflows/e2e-smoke.yml
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --frozen-lockfile # ⬅ deps
      - run: yarn build # ⬅ เพิ่ม build Vite **สำคัญ**

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run smoke tests
        run: npx playwright test --grep @smoke # ไม่ต้อง --project ก็ได้แล้ว

