# .github/workflows/e2e-smoke.yml
name: E2E - Smoke

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'e2e/**'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ให้ Playwright เห็น commit history เผื่อ trace

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --frozen-lockfile

      # ดาวน์โหลด Chrome-headless ที่ Playwright ใช้
      - run: npx playwright install --with-deps chromium

      # 👉 รันเฉพาะ smoke tag
      - run: yarn e2e:smoke
