# .github/workflows/e2e-full.yml
name: E2E - Full

on:
  workflow_run:
    workflows: ['E2E - Smoke'] # เริ่มรันต่อเมื่อ Smoke ผ่าน
    types: [completed]
    branches: [main]
  push:
    branches: [main] # push เข้า main ก็รัน
  schedule:
    - cron: '0 3 * * *' # nightly 03:00 UTC (10:00 ICT)
  workflow_dispatch: # กดรันเองได้

jobs:
  full:
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
      || github.event_name != 'workflow_run'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Node + Yarn cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      # 3) Install & Build
      - run: yarn install --frozen-lockfile
      - run: yarn build # ต้อง build ก่อน webServer

      # 4) ติดตั้ง browser ทั้งหมด
      - name: Install Playwright browsers (all)
        run: npx playwright install --with-deps

      - name: Run full E2E suite
        run: npx playwright test --grep @full

      # 6) อัปโหลดรีพอร์ตเสมอ
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
