# .github/workflows/e2e-smoke.yml
name: E2E - Smoke

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main] # 👉 base branch = main
    paths:
      - 'src/components/ui/**'
      - 'e2e/**'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - run: yarn install --frozen-lockfile

      - name: Install Playwright browsers (chromium only)
        run: npx playwright install --with-deps chromium

      - name: Run smoke tests
        run: npx playwright test --project=chromium --grep @smoke
